# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-19 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinaevent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='major',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
