# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-19 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chinaevent', '0002_candidate_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='info_src',
            field=models.CharField(default='N.A', max_length=200),
        ),
    ]
