# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-09-08 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import recruitment_campaign.models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_campaign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignOnlineApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(max_length=255)),
                ('workplace', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=30)),
                ('university', models.CharField(blank=True, max_length=100, null=True)),
                ('school', models.CharField(blank=True, max_length=200, null=True)),
                ('major', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('resume', models.FileField(blank=True, upload_to=recruitment_campaign.models.user_resume_path)),
                ('info_src', models.CharField(default='N.A', max_length=200)),
                ('start_time', models.DateField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default=b'NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('need_work_pass', models.CharField(blank=True, default='Yes', max_length=32)),
            ],
        ),
    ]
