# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-09-16 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment_campaign', '0002_campaignonlineapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignonlineapplication',
            name='need_work_pass',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
