# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-24 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('DEV', 'Developer'),
                                                       ('QRES', 'Quantitative Researcher'),
                                                       ('FQRES', 'Fundamental Quantitative Researcher')],
                                              default='DEV',
                                              max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('university', models.CharField(blank=True, max_length=100, null=True)),
                ('major', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('resume', models.FileField(blank=True, upload_to=main.models.user_resume_path)),
                ('status', models.CharField(choices=[('NEW', 'NEW'),
                                                     ('PASS_RESUME', 'PASS RESUME'),
                                                     ('FAIL_RESUME', 'FAIL RESUME'),
                                                     ('PASS_TEST', 'PASS TEST'),
                                                     ('FAIL_TEST', 'FAIL TEST')],
                                            default='NEW',
                                            max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashstr', models.CharField(max_length=100, unique=True)),
                ('version', models.CharField(choices=[('EN', 'English'),
                                                      ('CN', 'Chinese')],
                                             default='EN',
                                             max_length=10)),
                ('datetime', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'),
                                                     ('SET', 'Set'),
                                                     ('SENT', 'Sent')],
                                            default='NEW',
                                            max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                     related_name='test_request',
                                                     to='main.OnlineApplication')),
            ],
        ),
    ]
