# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-15 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineapplication',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'),
                                            ('PASS_RESUME', 'PASS RESUME'),
                                            ('FAIL_RESUME', 'FAIL RESUME'),
                                            ('PASS_TEST', 'PASS TEST'),
                                            ('FAIL_TEST', 'FAIL TEST'),
                                            ('DNF_TEST', 'DNF TEST')],
                                   default='NEW',
                                   max_length=20),
        ),
    ]
