# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-19 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170915_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineapplication',
            name='info_src',
            field=models.CharField(default='N.A', max_length=200),
        ),
    ]
