# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-25 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_onlineapplication_info_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineapplication',
            name='school',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
