# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-11 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180830_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineapplication',
            name='position',
            field=models.CharField(choices=[('DEV', 'Developer'), ('DATA_ENGINEER', 'Data Engineer'), ('OP_SPECIALIST', 'Operation Specialist'), ('QRES', 'Quantitative Researcher'), ('FQRES', 'Fundamental Quantitative Researcher'), ('INTERN_QRES', 'Quantitative Researcher (Internship)')], default='DEV', max_length=20),
        ),
    ]
