# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-19 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180913_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineapplication',
            name='is_onsite_recruiment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='onlineapplication',
            name='test_site',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
