# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-30 10:31
from __future__ import unicode_literals

from django.db import migrations
from main.models import OnlineApplication
from main.types import (
    OldJobPosition,
    JobPosition,
    JobType,
)

INTERNSHIPS = (
    (OldJobPosition.INTERN_FQ_RESEARCHER.value, (JobPosition.FQRES.name, JobType.FULLTIME_INTERNSHIP.name)),
    (OldJobPosition.INTERN_Q_RESEARCHER.value, (JobPosition.QRES.name, JobType.FULLTIME_INTERNSHIP.name)),
    (OldJobPosition.INTERN_DATA_ENGINEER.value, (JobPosition.DATA_ENGINEER.name, JobType.FULLTIME_INTERNSHIP.name)),
    (OldJobPosition.INTERN_DEVELOPER.value, (JobPosition.DEV.name, JobType.FULLTIME_INTERNSHIP.name)),
)


def convert_application_position(apps, schema_editor):
    """
    The main.models.OnlineApplication is added two more fields that are typ(type: could be
    part-time/full-time internship, full-time job) and workplace(could be shanghai, singapore or remote).
    So this function will determine typ of exist objects by position name and replace the position name
    with position name without "internship" word. The workplace should be always singapore for every
    exist objects.

    (position)              => (position, typ, workplace='Singapore')
    "DEV"                   => ("DEV", "Full-time Job")
    "DATA_ENGINEER"         => ("DATA_ENGINEER", "Full-time Job")
    "OP_SPECIALIST"         => ("OP_SPECIALIST", "Full-time job")
    "QRES"                  => ("QRES", "Full-time Job")
    "FQRES"                 => ("FQRES", "Full-time Job")
    "INTERN_FQRES"          => ("FQRES", "Full-time Internship")
    "INTERN_QRES"           => ("QRES", "Full-time Internship")
    "INTERN_DATA_ENGINEER"  => ("DATA_ENGINEER", "Full-time Internship")
    "INTERN_DEVELOPER"      => ("DEVELOPER", "Full-time Internship")
    """
    for internship in INTERNSHIPS:
        OnlineApplication.objects.filter(position=internship[0]).update(position=internship[1][0], typ=internship[1][1])


def reverse_application_position(apps, schema_editor):
    """
    This function only for error-free reversation but data is not reversed actually.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190830_1830'),
    ]

    operations = [
        migrations.RunPython(code=convert_application_position, reverse_code=reverse_application_position)
    ]
