# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-06 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190830_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='openjob',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='onlineapplication',
            name='position',
            field=models.CharField(default=b'Developer', max_length=255),
        ),
        migrations.AlterField(
            model_name='onlineapplication',
            name='start_time',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='onlineapplication',
            name='typ',
            field=models.CharField(default=b'FULLTIME_JOB', max_length=255),
        ),
        migrations.AlterField(
            model_name='onlineapplication',
            name='workplace',
            field=models.CharField(default=b'SINGAPORE', max_length=255),
        ),
        migrations.AlterField(
            model_name='openjob',
            name='typ',
            field=models.CharField(choices=[(b'FULLTIME_INTERNSHIP', b'Full-time Internship'),
                                            (b'FULLTIME_JOB', b'Full-time Job'),
                                            (b'INTERNSHIP', b'Internship'),
                                            (b'PARTTIME_INTERNSHIP', b'Part-time Internship')],
                                   max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='openjob',
            unique_together=set([('position', 'typ', 'workplace')]),
        ),
        migrations.AlterIndexTogether(
            name='openjob',
            index_together=set([('position',), ('position', 'typ')]),
        ),
    ]
