# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-11 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190906_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='openjob',
            name='test_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='token',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='token_status',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
