# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-03-18 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190911_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openjob',
            name='position',
            field=models.CharField(choices=[(b'DATA_ENGINEER', b'Data Engineer'), (b'DEV', b'Developer'), (b'FSDEV', b'Full-Stack Web Developer'), (b'FQRES', b'Fundamental Quantitative Researcher'), (b'OP_SPECIALIST', b'Operation Specialist'), (b'QRES', b'Quantitative Researcher')], max_length=255),
        ),
    ]
