# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-06-05 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200318_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openjob',
            name='position',
            field=models.CharField(choices=[(b'DATA_ANALYST', b'Data Analyst'),
                                            (b'DATA_ENGINEER', b'Data Engineer'),
                                            (b'DEV', b'Developer'),
                                            (b'FSDEV', b'Full-Stack Web Developer'),
                                            (b'FQRES', b'Fundamental Quantitative Researcher'),
                                            (b'OP_SPECIALIST', b'Operation Specialist'),
                                            (b'QRES', b'Quantitative Researcher'),
                                            (b'SYSAD', b'System Administrator')],
                                   max_length=255),
        ),
    ]
