# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-11-17 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20200928_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openjob',
            name='position',
            field=models.CharField(choices=[(b'DATA_ENGINEER', b'Data Engineer'), (b'DEV', b'Developer'), (b'FPGA_ENGINEER', b'FPGA Engineer'), (b'FSDEV', b'Full-Stack Developer'), (b'FQRES', b'Fundamental Quantitative Researcher'), (b'FRES', b'Fundamental Researcher'), (b'QRES', b'Quantitative Researcher'), (b'SYSAD', b'System Administrator'), (b'OP_SPECIALIST', b'Trading Support Engineer')], max_length=255),
        ),
    ]
