# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-02-23 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20201130_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='openjob',
            name='description',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AlterField(
            model_name='onlineapplication',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'),
                                            ('PASS_RESUME', 'PASS RESUME'),
                                            ('FAIL_RESUME', 'FAIL RESUME'),
                                            ('PASS_TEST', 'PASS TEST'),
                                            ('FAIL_TEST', 'FAIL TEST'),
                                            ('DNF_TEST', 'DNF TEST'),
                                            ('campaign', 'From campagins'),
                                            ('other', 'Other')],
                                   default='NEW',
                                   max_length=20),
        ),
        migrations.AlterField(
            model_name='openjob',
            name='position',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='openjob',
            name='typ',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='openjob',
            name='workplace',
            field=models.CharField(max_length=255),
        ),
    ]
