# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2021-08-12 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210223_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='openjob',
            name='test_duration',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
