# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-02-20 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_openjob_test_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineapplication',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
